/* eslint-disable no-plusplus */
const Book = require('../models/book');
const Category = require('../models/category');
// const User = require('../models/user')

const sdCategories = [{ category: 'Police' },
{ category: 'Thriller' },
{ category: 'Romantic' },
{ category: 'Adventure' },
{ category: 'Terror' },
{ category: 'Fiction' },
{ category: 'Reality' },
{ category: 'Science fiction' },
{ category: 'Investigation' },
{ category: 'Biographical' },
{ category: 'Childish' },
{ category: 'Self-help' },
{ category: 'Erotica' },
{ category: 'Home' },
{ category: 'Encyclopedia' },
{ category: 'Manual' },
{ category: 'Politics' },
{ category: 'Economy' },
{ category: 'Marketing' },
{ category: 'Society' },
{ category: 'sports' },
{ category: 'Travel' },
{ category: 'Culture' }];

const sdBooks = [
  {
    name: 'Spermophilus tridecemlineatus',
    author: 'Standford Mapham',
    year: 2005,
    editorial: 'Military/Government/Technical',
    description: 'ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis',
    sold: 140,
    price: 243.28,
    stock: 184,
  }, {
    name: 'Ovis dalli stonei',
    author: 'Cordell Dawid',
    year: 2007,
    editorial: 'Industrial Machinery/Components',
    description: 'odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla',
    sold: 1,
    price: 1741.2,
    stock: 6,
  }, {
    name: 'Lepus arcticus',
    author: 'Reinwald Cawdell',
    year: 2005,
    editorial: 'n/a',
    description: 'odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras',
    sold: 14,
    price: 1554.35,
    stock: 5,
  }, {
    name: 'Ephipplorhynchus senegalensis',
    author: 'Zacharia Strood',
    year: 1991,
    editorial: 'Mining & Quarrying of Nonmetallic Minerals (No Fuels)',
    description: 'curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros',
    sold: 142,
    price: 293.51,
    stock: 74,
  }, {
    name: 'Alopex lagopus',
    author: 'Elyssa Beranek',
    year: 2004,
    editorial: 'n/a',
    description: 'nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas',
    sold: 167,
    price: 1296.36,
    stock: 62,
  }, {
    name: 'Sciurus vulgaris',
    author: 'Dorisa Nugent',
    year: 2006,
    editorial: 'n/a',
    description: 'tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui',
    sold: 138,
    price: 1718.62,
    stock: 132,
  }, {
    name: 'Corvus albus',
    author: 'Ceil Geeritz',
    year: 2005,
    editorial: 'n/a',
    description: 'blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare',
    sold: 85,
    price: 1565.69,
    stock: 144,
  }, {
    name: 'Cacatua tenuirostris',
    author: 'Turner Kissick',
    year: 2009,
    editorial: 'Consumer Specialties',
    description: 'metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna',
    sold: 47,
    price: 266.4,
    stock: 175,
  }, {
    name: 'Zosterops pallidus',
    author: 'Kylen Garwood',
    year: 1984,
    editorial: 'Multi-Sector Companies',
    description: 'neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse',
    sold: 187,
    price: 755.73,
    stock: 132,
  }, {
    name: 'Ratufa indica',
    author: 'Geno Coot',
    year: 2006,
    editorial: 'Electrical Products',
    description: 'curabitur in libero ut massa volutpat convallis morbi odio odio',
    sold: 193,
    price: 893.34,
    stock: 55,
  }, {
    name: 'Phoca vitulina',
    author: 'Van Frean',
    year: 2001,
    editorial: 'Specialty Insurers',
    description: 'tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus',
    sold: 90,
    price: 698.35,
    stock: 2,
  }, {
    name: 'Odocoilenaus virginianus',
    author: 'Alric Claiton',
    year: 2000,
    editorial: 'Specialty Chemicals',
    description: 'amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque',
    sold: 68,
    price: 1293.66,
    stock: 53,
  }, {
    name: 'Chlamydosaurus kingii',
    author: 'Cherish Le Barr',
    year: 1986,
    editorial: 'Finance: Consumer Services',
    description: 'nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris',
    sold: 197,
    price: 151.86,
    stock: 38,
  }, {
    name: 'Turtur chalcospilos',
    author: 'Ferdinand Dwelly',
    year: 1995,
    editorial: 'Shoe Manufacturing',
    description: 'justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus',
    sold: 57,
    price: 543.02,
    stock: 40,
  }, {
    name: 'Cervus canadensis',
    author: 'Celestyna Nestle',
    year: 2008,
    editorial: 'n/a',
    description: 'venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris',
    sold: 187,
    price: 1595.7,
    stock: 151,
  }, {
    name: 'Ceratotherium simum',
    author: 'Gabriellia Dymick',
    year: 2002,
    editorial: 'n/a',
    description: 'lacinia sapien quis libero nullam sit amet turpis elementum ligula',
    sold: 57,
    price: 1054.18,
    stock: 178,
  }, {
    name: 'Mirounga angustirostris',
    author: 'Halley Bouts',
    year: 1993,
    editorial: 'Military/Government/Technical',
    description: 'vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus',
    sold: 120,
    price: 675.88,
    stock: 166,
  }, {
    name: 'Felis silvestris lybica',
    author: 'Kienan Hiseman',
    year: 1993,
    editorial: 'Steel/Iron Ore',
    description: 'non quam nec dui luctus rutrum nulla tellus in sagittis dui vel',
    sold: 148,
    price: 1958.89,
    stock: 154,
  }, {
    name: 'Threskionis aethiopicus',
    author: 'Ruthie Gartin',
    year: 2011,
    editorial: 'n/a',
    description: 'mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet',
    sold: 118,
    price: 830.09,
    stock: 188,
  }, {
    name: 'Orcinus orca',
    author: 'Arlen Dahlback',
    year: 1993,
    editorial: 'Electrical Products',
    description: 'nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna',
    sold: 81,
    price: 691.7,
    stock: 28,
  }, {
    name: 'Eudyptula minor',
    author: 'Rickey Georgeot',
    year: 2005,
    editorial: 'Major Pharmaceuticals',
    description: 'luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo',
    sold: 41,
    price: 1761.08,
    stock: 180,
  }, {
    name: 'Uraeginthus bengalus',
    author: 'Matthias Toghill',
    year: 1987,
    editorial: 'Transportation Services',
    description: 'magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis',
    sold: 178,
    price: 1409.71,
    stock: 170,
  }, {
    name: 'Streptopelia decipiens',
    author: 'Myrta Hamshar',
    year: 2001,
    editorial: 'Marine Transportation',
    description: 'aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu',
    sold: 186,
    price: 516.77,
    stock: 137,
  }, {
    name: 'Buteo regalis',
    author: 'Esdras Laurie',
    year: 2012,
    editorial: 'Finance: Consumer Services',
    description: 'nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate',
    sold: 9,
    price: 1681.95,
    stock: 5,
  }, {
    name: 'Paraxerus cepapi',
    author: 'Marleen Wharfe',
    year: 2012,
    editorial: 'n/a',
    description: 'penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et',
    sold: 85,
    price: 823.93,
    stock: 188,
  }, {
    name: 'Varanus salvator',
    author: 'Valentia Royson',
    year: 1993,
    editorial: 'EDP Services',
    description: 'dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo',
    sold: 13,
    price: 1435.03,
    stock: 67,
  }, {
    name: 'Macaca radiata',
    author: 'Alessandra Waggatt',
    year: 1996,
    editorial: 'Business Services',
    description: 'fusce posuere felis sed lacus morbi sem mauris laoreet ut',
    sold: 43,
    price: 1036.62,
    stock: 1,
  }, {
    name: 'Chauna torquata',
    author: 'Burtie Macallam',
    year: 1999,
    editorial: 'Major Pharmaceuticals',
    description: 'magna at nunc commodo placerat praesent blandit nam nulla integer',
    sold: 73,
    price: 55.63,
    stock: 177,
  }, {
    name: 'Graspus graspus',
    author: 'Gussy Antonchik',
    year: 1989,
    editorial: 'Professional Services',
    description: 'at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget',
    sold: 185,
    price: 1146.55,
    stock: 16,
  }, {
    name: 'Felis silvestris lybica',
    author: 'Phillipp Orae',
    year: 1989,
    editorial: 'n/a',
    description: 'dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac',
    sold: 159,
    price: 794.22,
    stock: 93,
  }, {
    name: 'Cracticus nigroagularis',
    author: "Katalin O' Clovan",
    year: 2004,
    editorial: 'n/a',
    description: 'sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet',
    sold: 1,
    price: 1400.58,
    stock: 81,
  }, {
    name: 'Mazama gouazoubira',
    author: 'Dorella Cowdery',
    year: 2001,
    editorial: 'Industrial Machinery/Components',
    description: 'vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem',
    sold: 173,
    price: 998.79,
    stock: 179,
  }, {
    name: 'Carduelis pinus',
    author: 'Romola Eldered',
    year: 2004,
    editorial: 'Agricultural Chemicals',
    description: 'sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis',
    sold: 166,
    price: 916.85,
    stock: 140,
  }, {
    name: 'Ara ararauna',
    author: 'Dulci Dewire',
    year: 2002,
    editorial: 'Major Banks',
    description: 'blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac',
    sold: 159,
    price: 1794.25,
    stock: 39,
  }, {
    name: 'Ara ararauna',
    author: 'Lorie Vernazza',
    year: 1990,
    editorial: 'Major Pharmaceuticals',
    description: 'et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit',
    sold: 158,
    price: 120.54,
    stock: 188,
  }, {
    name: 'Varanus sp.',
    author: 'Salem Rickaert',
    year: 2006,
    editorial: 'n/a',
    description: 'justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat',
    sold: 6,
    price: 528.94,
    stock: 125,
  }, {
    name: 'Globicephala melas',
    author: 'Perla La Croce',
    year: 2001,
    editorial: 'n/a',
    description: 'odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia',
    sold: 122,
    price: 1781.64,
    stock: 50,
  }, {
    name: 'Panthera tigris',
    author: 'Gabbey Sabati',
    year: 2009,
    editorial: 'Property-Casualty Insurers',
    description: 'vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus',
    sold: 84,
    price: 271.52,
    stock: 120,
  }, {
    name: 'Milvago chimachima',
    author: 'Kerr Meakes',
    year: 1998,
    editorial: 'n/a',
    description: 'rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet',
    sold: 67,
    price: 1236.29,
    stock: 23,
  }, {
    name: 'Casmerodius albus',
    author: 'Hervey Goundsy',
    year: 1998,
    editorial: 'n/a',
    description: 'justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere',
    sold: 104,
    price: 703.08,
    stock: 27,
  }, {
    name: 'Anser anser',
    author: 'Anitra Pinnick',
    year: 1992,
    editorial: 'Biotechnology: Electromedical & Electrotherapeutic Apparatus',
    description: 'pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget',
    sold: 121,
    price: 173.15,
    stock: 64,
  }, {
    name: 'Kobus vardonii vardoni',
    author: 'Carrie Brereton',
    year: 1997,
    editorial: 'Major Pharmaceuticals',
    description: 'augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus',
    sold: 160,
    price: 391.81,
    stock: 90,
  }, {
    name: 'Gyps bengalensis',
    author: "Fayette O'Scollee",
    year: 1996,
    editorial: 'Major Pharmaceuticals',
    description: 'nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices',
    sold: 123,
    price: 1841.2,
    stock: 152,
  }, {
    name: 'Hippotragus equinus',
    author: 'Britta Utteridge',
    year: 1996,
    editorial: 'n/a',
    description: 'in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna',
    sold: 76,
    price: 295.53,
    stock: 124,
  }, {
    name: 'Ciconia episcopus',
    author: 'Morgen Pinchbeck',
    year: 1992,
    editorial: 'Oil & Gas Production',
    description: 'nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante',
    sold: 5,
    price: 1592.68,
    stock: 22,
  }, {
    name: 'Gymnorhina tibicen',
    author: 'Lisette Haswell',
    year: 1985,
    editorial: 'Business Services',
    description: 'lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem',
    sold: 158,
    price: 1530.36,
    stock: 146,
  }, {
    name: 'Bassariscus astutus',
    author: 'Lancelot Wofenden',
    year: 2011,
    editorial: 'n/a',
    description: 'volutpat eleifend donec ut dolor morbi vel lectus in quam',
    sold: 73,
    price: 1668.53,
    stock: 92,
  }, {
    name: 'Pseudalopex gymnocercus',
    author: 'Pauli Petrik',
    year: 2008,
    editorial: 'n/a',
    description: 'orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit',
    sold: 148,
    price: 1547.23,
    stock: 56,
  }, {
    name: 'Ateles paniscus',
    author: 'Kelsey Hatherell',
    year: 2007,
    editorial: 'n/a',
    description: 'purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea',
    sold: 73,
    price: 110.28,
    stock: 146,
  }, {
    name: 'Mazama gouazoubira',
    author: 'Hanson Davern',
    year: 1997,
    editorial: 'n/a',
    description: 'ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut',
    sold: 200,
    price: 234.79,
    stock: 53,
  }, {
    name: 'Antilocapra americana',
    author: 'Doralyn Wessel',
    year: 1993,
    editorial: 'Computer Software: Prepackaged Software',
    description: 'at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel',
    sold: 73,
    price: 1966.97,
    stock: 36,
  }, {
    name: 'Corvus albicollis',
    author: 'Oliy Rudiger',
    year: 2013,
    editorial: 'Property-Casualty Insurers',
    description: 'mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam nam tristique tortor',
    sold: 97,
    price: 1756.94,
    stock: 109,
  }, {
    name: 'Paraxerus cepapi',
    author: 'Sherill Thamelt',
    year: 1996,
    editorial: 'Industrial Machinery/Components',
    description: 'curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu',
    sold: 180,
    price: 1433.56,
    stock: 27,
  }, {
    name: 'unavailable',
    author: 'Normy Dilgarno',
    year: 2012,
    editorial: 'Television Services',
    description: 'aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci',
    sold: 119,
    price: 123.65,
    stock: 163,
  }, {
    name: 'Gyps bengalensis',
    author: 'Juliana Reavell',
    year: 2010,
    editorial: 'Finance: Consumer Services',
    description: 'semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero',
    sold: 146,
    price: 452.28,
    stock: 68,
  }, {
    name: 'Colaptes campestroides',
    author: 'Nicoline Delooze',
    year: 1984,
    editorial: 'Business Services',
    description: 'luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium',
    sold: 127,
    price: 1694.0,
    stock: 168,
  }, {
    name: 'Rangifer tarandus',
    author: 'Xavier Mallock',
    year: 2010,
    editorial: 'Business Services',
    description: 'ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed',
    sold: 18,
    price: 433.06,
    stock: 122,
  }, {
    name: 'Ovis ammon',
    author: 'Eldridge Wemyss',
    year: 1999,
    editorial: 'Engineering & Construction',
    description: 'fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti',
    sold: 95,
    price: 1862.96,
    stock: 140,
  }, {
    name: 'Choloepus hoffmani',
    author: 'Emmye Southcoat',
    year: 2005,
    editorial: 'Services-Misc. Amusement & Recreation',
    description: 'libero nam dui proin leo odio porttitor id consequat in consequat ut nulla',
    sold: 85,
    price: 1025.19,
    stock: 76,
  }, {
    name: 'Taxidea taxus',
    author: 'Loise Purser',
    year: 1977,
    editorial: 'Industrial Machinery/Components',
    description: 'convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim',
    sold: 79,
    price: 824.06,
    stock: 93,
  }, {
    name: 'Cercopithecus aethiops',
    author: 'Brock Delph',
    year: 1999,
    editorial: 'Major Banks',
    description: 'justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea',
    sold: 98,
    price: 148.02,
    stock: 46,
  }, {
    name: 'Lamprotornis nitens',
    author: 'Martainn Wonham',
    year: 1996,
    editorial: 'Metal Fabrications',
    description: 'lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet',
    sold: 155,
    price: 607.52,
    stock: 184,
  }, {
    name: 'Perameles nasuta',
    author: 'Bevin Errigo',
    year: 2011,
    editorial: 'Computer Communications Equipment',
    description: 'in est risus auctor sed tristique in tempus sit amet',
    sold: 140,
    price: 1005.43,
    stock: 111,
  }, {
    name: 'Lophoaetus occipitalis',
    author: 'Troy Whitton',
    year: 1995,
    editorial: 'Property-Casualty Insurers',
    description: 'nec nisi volutpat eleifend donec ut dolor morbi vel lectus',
    sold: 93,
    price: 1069.75,
    stock: 195,
  }, {
    name: 'Mazama americana',
    author: 'Carilyn Ayres',
    year: 1996,
    editorial: 'Military/Government/Technical',
    description: 'vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis',
    sold: 157,
    price: 1971.84,
    stock: 95,
  }, {
    name: 'Limnocorax flavirostra',
    author: 'Filmore Seven',
    year: 2008,
    editorial: 'Major Pharmaceuticals',
    description: 'dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit',
    sold: 142,
    price: 1446.21,
    stock: 2,
  }, {
    name: 'Loxodonta africana',
    author: 'Natalya De Gregoli',
    year: 1992,
    editorial: 'Property-Casualty Insurers',
    description: 'in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat',
    sold: 67,
    price: 790.18,
    stock: 63,
  }, {
    name: 'Litrocranius walleri',
    author: 'Tildy McNern',
    year: 1996,
    editorial: 'n/a',
    description: 'nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est',
    sold: 159,
    price: 196.9,
    stock: 191,
  }, {
    name: 'Petaurus breviceps',
    author: 'Alberik Tytler',
    year: 1990,
    editorial: 'Business Services',
    description: 'adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien',
    sold: 11,
    price: 406.01,
    stock: 177,
  }, {
    name: 'Larus fuliginosus',
    author: 'Adrianna Sacher',
    year: 2003,
    editorial: 'Major Banks',
    description: 'odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit',
    sold: 186,
    price: 445.87,
    stock: 43,
  }, {
    name: 'Ammospermophilus nelsoni',
    author: 'Katerina Meeron',
    year: 2000,
    editorial: 'Oil/Gas Transmission',
    description: 'nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi',
    sold: 77,
    price: 257.01,
    stock: 79,
  }, {
    name: 'Macaca fuscata',
    author: 'Arlee Wreakes',
    year: 1992,
    editorial: 'Major Banks',
    description: 'dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et',
    sold: 161,
    price: 1528.77,
    stock: 63,
  }, {
    name: 'Terathopius ecaudatus',
    author: 'Rice Whitrod',
    year: 1992,
    editorial: 'Meat/Poultry/Fish',
    description: 'quisque arcu libero rutrum ac lobortis vel dapibus at diam',
    sold: 86,
    price: 896.71,
    stock: 130,
  }, {
    name: 'Drymarchon corias couperi',
    author: 'Birdie Cockland',
    year: 2008,
    editorial: 'EDP Services',
    description: 'molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget',
    sold: 192,
    price: 552.2,
    stock: 74,
  }, {
    name: 'Genetta genetta',
    author: 'Helenelizabeth Fullylove',
    year: 2012,
    editorial: 'n/a',
    description: 'id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie',
    sold: 16,
    price: 1095.55,
    stock: 112,
  }, {
    name: 'Fratercula corniculata',
    author: 'Olvan Greenhouse',
    year: 2012,
    editorial: 'n/a',
    description: 'vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus',
    sold: 33,
    price: 1175.15,
    stock: 14,
  }, {
    name: 'Mazama gouazoubira',
    author: 'Tommie Foote',
    year: 2005,
    editorial: 'Beverages (Production/Distribution)',
    description: 'pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum',
    sold: 182,
    price: 775.8,
    stock: 194,
  }, {
    name: 'Ciconia episcopus',
    author: 'Muhammad Berthelet',
    year: 1967,
    editorial: 'Industrial Machinery/Components',
    description: 'sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit',
    sold: 135,
    price: 1584.95,
    stock: 159,
  }, {
    name: 'Semnopithecus entellus',
    author: 'Dave Antonikov',
    year: 2005,
    editorial: 'n/a',
    description: 'in ante vestibulum ante ipsum primis in faucibus orci luctus et',
    sold: 118,
    price: 1023.27,
    stock: 196,
  }, {
    name: 'unavailable',
    author: 'Fannie Kowal',
    year: 2004,
    editorial: 'n/a',
    description: 'mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit',
    sold: 66,
    price: 1337.38,
    stock: 53,
  }, {
    name: 'Acanthaster planci',
    author: 'Viviene Tremayne',
    year: 1996,
    editorial: 'n/a',
    description: 'congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu',
    sold: 102,
    price: 643.41,
    stock: 87,
  }, {
    name: 'Odocoilenaus virginianus',
    author: 'Penrod Jeary',
    year: 2011,
    editorial: 'n/a',
    description: 'amet sem fusce consequat nulla nisl nunc nisl duis bibendum',
    sold: 63,
    price: 150.35,
    stock: 198,
  }, {
    name: 'Paroaria gularis',
    author: 'Adela Haymes',
    year: 2000,
    editorial: 'n/a',
    description: 'justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in',
    sold: 114,
    price: 182.58,
    stock: 90,
  }, {
    name: 'Ara chloroptera',
    author: 'Roderick Ezzle',
    year: 2007,
    editorial: 'Semiconductors',
    description: 'in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus',
    sold: 14,
    price: 1433.03,
    stock: 146,
  }, {
    name: 'Sciurus niger',
    author: 'Vivyanne Whiles',
    year: 2007,
    editorial: 'Major Banks',
    description: 'nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris',
    sold: 162,
    price: 1246.32,
    stock: 132,
  }, {
    name: 'Mungos mungo',
    author: 'Gavrielle Hodgin',
    year: 2010,
    editorial: 'Computer Software: Prepackaged Software',
    description: 'varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla',
    sold: 160,
    price: 1260.43,
    stock: 114,
  }, {
    name: 'Pteropus rufus',
    author: 'Chev Kenewell',
    year: 2000,
    editorial: 'Real Estate Investment Trusts',
    description: 'tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac',
    sold: 115,
    price: 1404.82,
    stock: 86,
  }, {
    name: 'Chlidonias leucopterus',
    author: 'Terrijo Leechman',
    year: 2010,
    editorial: 'Major Pharmaceuticals',
    description: 'commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id',
    sold: 67,
    price: 607.96,
    stock: 131,
  }, {
    name: 'Gyps fulvus',
    author: 'Jackie Jerwood',
    year: 2006,
    editorial: 'Medical/Dental Instruments',
    description: 'justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam',
    sold: 69,
    price: 673.63,
    stock: 176,
  }, {
    name: 'Felis concolor',
    author: 'Clarey Witul',
    year: 1989,
    editorial: 'Building Products',
    description: 'dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus',
    sold: 73,
    price: 842.53,
    stock: 150,
  }, {
    name: 'Felis caracal',
    author: 'Rinaldo Karleman',
    year: 2005,
    editorial: 'Major Banks',
    description: 'justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique',
    sold: 188,
    price: 437.71,
    stock: 34,
  }, {
    name: 'Varanus sp.',
    author: 'Marigold Coneau',
    year: 1997,
    editorial: 'Property-Casualty Insurers',
    description: 'viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae',
    sold: 39,
    price: 364.73,
    stock: 154,
  }, {
    name: 'Dusicyon thous',
    author: 'Hana Ewbach',
    year: 2011,
    editorial: 'Steel/Iron Ore',
    description: 'sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam',
    sold: 31,
    price: 1578.47,
    stock: 83,
  }, {
    name: 'Anitibyx armatus',
    author: 'Petey Yule',
    year: 2010,
    editorial: 'Restaurants',
    description: 'turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante',
    sold: 87,
    price: 27.29,
    stock: 133,
  }, {
    name: 'Phoca vitulina',
    author: 'Tadeas Creboe',
    year: 1998,
    editorial: 'n/a',
    description: 'tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris',
    sold: 30,
    price: 863.96,
    stock: 59,
  }, {
    name: 'Anthropoides paradisea',
    author: 'Shirl Ruddiman',
    year: 1967,
    editorial: 'Electric Utilities: Central',
    description: 'odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a',
    sold: 101,
    price: 316.7,
    stock: 127,
  }, {
    name: 'Felis concolor',
    author: 'Dian Jenton',
    year: 2004,
    editorial: 'Major Pharmaceuticals',
    description: 'primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat',
    sold: 147,
    price: 1923.42,
    stock: 64,
  }, {
    name: 'unavailable',
    author: 'Pearla Danilishin',
    year: 2006,
    editorial: 'Farming/Seeds/Milling',
    description: 'eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula',
    sold: 161,
    price: 1477.51,
    stock: 3,
  }, {
    name: 'Eremophila alpestris',
    author: 'Sabine Varren',
    year: 2005,
    editorial: 'Clothing/Shoe/Accessory Stores',
    description: 'in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin',
    sold: 110,
    price: 617.99,
    stock: 56,
  }, {
    name: 'Buteo galapagoensis',
    author: 'Ajay McKew',
    year: 2005,
    editorial: 'Integrated oil Companies',
    description: 'platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi',
    sold: 106,
    price: 1531.52,
    stock: 122,
  }];

sdCategories.map(cat => Category.create(cat));

sdBooks.map(sdBook => Book.create(sdBook)
  .then((book) => {
    // Random quantity of categories
    const nCat = Math.floor((Math.random() * 3) + 1);
    for (let i = 0; i < nCat; i++) {
      // Random categorie selector
      const tCat = Math.floor((Math.random() * 23) + 1);
      Category.findOne({ where: { id: tCat } })
        .then(cat => cat.addBook(book));
    }
  }))